#!/usr/bin/env python3
"""
env_sync.py — assemble the verifier's runtime env from .env + gate.config.json + server.state.json.

  python3 env_sync.py --local     write app/.env.local (mode 600) for local runs (migrate, register-commands, next dev)
  python3 env_sync.py --vercel    push the same values to the linked Vercel project (production + preview)
  python3 env_sync.py --show      print masked
  python3 env_sync.py --pull-db   after `vercel integration add neon`: copy DATABASE_URL from the Vercel project into .env

SESSION_SECRET and CRON_SECRET are generated once and kept in .env so redeploys don't log everyone out.
"""
import json, os, secrets, subprocess, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
APP = ROOT / "app"
SECRET_KEYS = {"DISCORD_BOT_TOKEN", "DISCORD_CLIENT_SECRET", "RPC_URL", "DATABASE_URL", "SESSION_SECRET", "CRON_SECRET"}

sys.path.insert(0, str(ROOT))
from intake import load_env, save_env, mask  # noqa: E402

def build(local: bool):
    env = load_env()
    cfg = json.load(open(ROOT / "gate.config.json"))
    state_path = ROOT / "server.state.json"
    state = json.load(open(state_path)) if state_path.exists() else {}
    if state.get("dry_run", True):
        print("⚠ server.state.json is from a dry run (or missing): tier role ids are placeholders until provision.py is applied")
    changed = False
    for k in ("SESSION_SECRET", "CRON_SECRET"):
        if not env.get(k):
            env[k] = secrets.token_hex(32); changed = True
    if changed:
        save_env(env)
    tiers = [{"role": t["role"], "min": t["min"], "role_id": t.get("role_id")} for t in state.get("tiers", [])] or \
            [{"role": t["role"], "min": t["min"], "role_id": None} for t in cfg["policy"]["tiers"]]
    origin = "http://localhost:3000" if local else f"https://{cfg['hosting']['verify_domain']}"
    out = {
        "DISCORD_BOT_TOKEN": env["DISCORD_BOT_TOKEN"],
        "DISCORD_APP_ID": env["DISCORD_APP_ID"],
        "DISCORD_PUBLIC_KEY": env["DISCORD_PUBLIC_KEY"],
        "DISCORD_CLIENT_SECRET": env.get("DISCORD_CLIENT_SECRET", ""),
        "DISCORD_GUILD_ID": env["DISCORD_GUILD_ID"],
        "RPC_URL": env["RPC_URL"],
        "COLLECTION_ADDRESS": cfg["collection"]["address"],
        "CHAIN_ID": "1" if cfg["network"] == "mainnet" else "11155111",
        "DATABASE_URL": env.get("DATABASE_URL", ""),
        "SESSION_SECRET": env["SESSION_SECRET"],
        "CRON_SECRET": env["CRON_SECRET"],
        "VERIFY_DOMAIN": cfg["hosting"]["verify_domain"],
        "PUBLIC_ORIGIN": origin,
        "GATE_TIERS": json.dumps(tiers, separators=(",", ":")),
        "AUDIT_CHANNEL_ID": state.get("audit_channel_id") or "",
        "VERIFY_CHANNEL_ID": state.get("verify_channel_id") or "",
        "LANDING_CHANNEL_ID": state.get("landing_channel_id") or "",
        "TEAM_ROLE_ID": state.get("team_role_id") or "",
        "PRUNE_DAYS": str(cfg["policy"].get("prune_days", 0)),
        "SWEEP_HOURS": str(cfg["policy"].get("sweep_hours", 6)),
        "PROJECT_NAME": cfg["project"],
    }
    return out

def write_local(out):
    p = APP / ".env.local"
    lines = ["# generated by ../env_sync.py --local — do not commit"]
    for k, v in out.items():
        # single quotes: dotenv takes the value literally (no escapes, no $VAR expansion)
        lines.append(f"{k}='{v}'" if "'" not in v else f'{k}="{v.replace(chr(92), chr(92)*2).replace(chr(34), chr(92)+chr(34))}"')
    fd = os.open(p, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, "w") as f:
        f.write("\n".join(lines) + "\n")
    os.chmod(p, 0o600)
    print(f"wrote {p} ({len(out)} vars, mode 600)")

def push_vercel(out):
    for k, v in out.items():
        if v == "":
            print(f"  skip {k} (empty)"); continue
        for target in ("production", "preview"):
            r = subprocess.run(["vercel", "env", "add", k, target, "--force", "--yes"], cwd=APP, input=v, text=True, capture_output=True)
            status = "ok" if r.returncode == 0 else f"FAILED: {(r.stderr or r.stdout).strip()[:160]}"
            print(f"  {k:<22} {target:<11} {status}")

def pull_db():
    """Neon (via Vercel Marketplace) injects DATABASE_URL into the project. Fetch it so nobody copies a secret by hand."""
    import tempfile
    tmp = Path(tempfile.mkstemp(prefix="vercel-env-", suffix=".env", dir=APP)[1])
    try:
        r = subprocess.run(["vercel", "env", "pull", tmp.name, "--environment=production", "--yes"], cwd=APP, capture_output=True, text=True)
        if r.returncode != 0:
            print("vercel env pull failed:", (r.stderr or r.stdout).strip()[:300]); return 1
        got = {}
        for line in tmp.read_text().splitlines():
            m = line.strip()
            if not m or m.startswith("#") or "=" not in m: continue
            k, v = m.split("=", 1); v = v.strip().strip('"').strip("'")
            got[k.strip()] = v
    finally:
        tmp.unlink(missing_ok=True)
    url = next((got[k] for k in ("DATABASE_URL", "POSTGRES_URL", "DATABASE_URL_UNPOOLED", "POSTGRES_URL_NON_POOLING") if got.get(k)), None)
    if not url:
        print("no DATABASE_URL in the Vercel project yet. Run `vercel integration add neon` from ~/discord-nft-gate/app first "
              "(keys present: " + ", ".join(sorted(k for k in got if "PG" in k or "POSTGRES" in k or "DATABASE" in k)) + ")")
        return 1
    env = load_env(); env["DATABASE_URL"] = url; save_env(env)
    cfg = json.load(open(ROOT / "gate.config.json")); cfg.setdefault("hosting", {})["database_url_set"] = True
    (ROOT / "gate.config.json").write_text(json.dumps(cfg, indent=2) + "\n")
    print(f"DATABASE_URL saved to .env ({mask(url)}, host {url.split('@')[-1].split('/')[0] if '@' in url else '?'})")
    write_local(build(local=True))
    return 0

def show(out):
    for k, v in out.items():
        print(f"  {k:<22} {mask(v) if k in SECRET_KEYS else v}")

if __name__ == "__main__":
    a = sys.argv[1:]
    if "--pull-db" in a:
        sys.exit(pull_db())
    if "--local" in a:
        write_local(build(local=True))
    elif "--vercel" in a:
        push_vercel(build(local=False))
    else:
        show(build(local=False))
